modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="meecreeps"
version="${version}"
displayName="MeeCreeps"
authors="McJty"
description='''Helpful creatures and a portal gun.'''
[[dependencies.meecreeps]]
modId="neoforge"
type="required"
versionRange="[21.1.249,)"
ordering="NONE"
side="BOTH"
[[dependencies.meecreeps]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.meecreeps]]
modId="mcjtylib"
type="required"
versionRange="[1.21-9.0.21.20,)"
ordering="AFTER"
side="BOTH"
[[dependencies.meecreeps]]
modId="theoneprobe"
type="optional"
versionRange="[1.21_neo-12.0.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.meecreeps]]
modId="interactionwheel"
type="optional"
versionRange="[1.20-4.0.0,)"
ordering="AFTER"
side="BOTH"
