modLoader="javafml"
license="MIT"
[[mods]]
modId="meecreeps"
version="${version}"
displayName="MeeCreeps"
authors="McJty"
description='''Helpful creatures and a portal gun.'''
[[dependencies.meecreeps]]
modId="neoforge"
type="required"
versionRange="[26.2.0.75,)"
ordering="NONE"
side="BOTH"
[[dependencies.meecreeps]]
modId="minecraft"
type="required"
versionRange="[26.2]"
ordering="NONE"
side="BOTH"
[[dependencies.meecreeps]]
modId="theoneprobe"
type="optional"
versionRange="[26.2_neo-15.0.1-2,)"
ordering="AFTER"
side="BOTH"
